### ISSUE TITLE
OSC(open sound control) Support

### ISSUE THREAD

**Issue by RuolunWeng** [khoih-prog/AsyncUDP_WT32_ETH01#2]
Dear all,

I'm opening this discussion to talk about the possibility of adding the OSC(open sound control) for this library. What I want to do is sending OSC message who is originally depending on UDP with WT32_ETH01, like I am not a specialist or programmer, I met the compatible problem when I want to use standard Arduino OSC library with this AsyncUDP library.
- OSC reference : https://www.arduino.cc/reference/en/libraries/osc/ 

Initial test was simple, based on this example of OSC and just want to replace their standard Arduino WifiUDP/EthernetUDP with AsyncUDP, but actually messages are not well formatted and dropped. So I suppose there should have some compatible issues, 
- OSC example for Arduino standard: https://github.com/CNMAT/OSC/blob/master/examples/ESP8266sendMessage/ESP8266sendMessage.ino
- error message during the reception of OSC:
udpreceive: OSC packet size (10) not a multiple of 4 bytes: dropping
udpreceive: OSC packet size (1) not a multiple of 4 bytes: dropping
udpreceive: OSC Bad message name string: DataAfterAlignedString: Incorrectly padded string.
Dropping entire message.

Anyone has some ideas?  
Thanks in advance

**Comment by khoih-prog** [comment]
Hi @RuolunWeng 

Thanks for your interest in the library.

So far, nobody has any idea to help yet after 2 weeks.

I'm afraid this use-case is too **special** to draw any interest.

I only can suggest you (or somebody) to convert the [**OSC** library](https://github.com/CNMAT/OSC) code to use [**AsyncUDP_WT32_ETH01** library](https://github.com/khoih-prog/AsyncUDP_WT32_ETH01) completely. 

**Adding the header inclusion is not enough to use Async**

For example, compare the [**AsyncUdpNTPClient** example](https://github.com/khoih-prog/AsyncUDP_WT32_ETH01/tree/main/examples/AsyncUdpNTPClient) with another Sync [**UdpNTPClient** example](https://github.com/khoih-prog/EthernetWebServer/tree/master/examples/UdpNTPClient), especially the `loop()`

https://github.com/khoih-prog/AsyncUDP_WT32_ETH01/blob/51930ae491c0250f041006dfcfe7da3144a13227/examples/AsyncUdpNTPClient/AsyncUdpNTPClient.ino#L162-L165

Finally, as this is not an issue of the library, I'm closing it now and suggest that you post on the [**Discussions**](https://github.com/khoih-prog/AsyncUDP_WT32_ETH01/discussions) next time for not-an-issue of the library.

Good Luck,
